### model
model_name_or_path: Qwen/Qwen2-7B-Instruct
weak_base_model:  Qwen/Qwen2-1.5B-Instruct
weak_aligned_model: your weak aligned model

### method
stage: wspo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
### dataset
dataset: ultrafeedback
template: default
cutoff_len: 4096
max_samples: 268694
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: qwen2.5_models/full/Qwen2-7B-Insturct_wspo_0.1
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000