### model
model_name_or_path: Qwen/Qwen2-1.5B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: ultrachat_200k
template: qwen
cutoff_len: 4096
max_samples: 2200000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: [save_path]
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 1000
